# Generated by Django 3.2 on 2021-05-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_type',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
    ]
