# Generated by Django 3.2 on 2021-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
