# Generated by Django 3.2 on 2021-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_brief',
            field=models.ImageField(default='static/main/img/logo.png', upload_to='static/main/img', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
