# Generated by Django 3.2 on 2021-05-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210529_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_brief',
            new_name='img',
        ),
    ]
