# Generated by Django 3.2 on 2021-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
    ]
