# Generated by Django 3.2 on 2021-05-31 14:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_receipt_has_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt_has_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Количество')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Товар')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.receipt', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ-продукт',
                'verbose_name_plural': 'Заказы-продукты',
                'unique_together': {('receipt_id', 'product_id')},
            },
        ),
    ]
