# Generated by Django 3.2 on 2021-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.CharField(default='ул. XXXXXXXXXXXX, XX.', max_length=50, verbose_name='Адрес'),
        ),
    ]
