# Generated by Django 3.2 on 2021-06-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_receipt_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='massage',
        ),
    ]
